-- DROP DATABASE chat;
CREATE DATABASE chat;

USE chat;

DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
  `objectId` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `username` INTEGER(20) NULL DEFAULT NULL,
  `message` VARCHAR(140) NULL DEFAULT NULL,
  `created_At` TIMESTAMP NULL DEFAULT NULL,
  `roomname` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`objectId`)
) COMMENT 'chatterbot';

DROP TABLE IF EXISTS `user_id`;

CREATE TABLE `user_id` (
  `user_id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`)
);

ALTER TABLE `messages` ADD FOREIGN KEY (username) REFERENCES `user_id` (`user_id`);
